org.gradle.jvmargs=-Xmx4096M
loom.ignoreDependencyLoomVersionValidation=true

minecraft_version=1.21.10
enabled_platforms=fabric,neoforge

minecraft_base_version=1.21.10

archives_base_name=accessories
mod_version=1.4.0-beta
maven_group=io.wispforest

# Libs
endec_version=0.1.11
endec_netty_version=0.1.5
endec_gson_version=0.1.6
endec_jankson_version=0.1.6

owo_version=0.12.24+1.21.9
jankson_version=1.2.2

owo_neo_version=0.12.26+1.21.9

fabric_loader_version=0.17.2
fabric_api_version=0.135.0+1.21.10
modmenu_version=16.0.0-rc.1

neoforge_version=21.10.16-beta

# Compat Mods
rei_version=20.0.811
arch_api=17.0.8
emi_version=1.1.18+1.21.1
jei_minecraft_version=1.21.1
jei_version=19.21.0.247

sodium_version=mc1.21.8-0.7.0

geckolib_minecraft_version=1.21.8
geckolib_version=5.2.2

curios_version=10.0.1+1.21.4

# Types: none, rei, emi, jei
item_viewer_type=none
