org.gradle.jvmargs=-Xmx4096M
loom.ignoreDependencyLoomVersionValidation=true

minecraft_version=1.21.4
enabled_platforms=fabric,neoforge

minecraft_base_version=1.21.4

archives_base_name=accessories
mod_version=1.2.10-beta
maven_group=io.wispforest

# Libs
endec_version=0.1.9
endec_netty_version=0.1.5
endec_gson_version=0.1.6
endec_jankson_version=0.1.6

owo_version=0.12.19+1.21.4
jankson_version=1.2.2

owo_neo_version=0.12.19-beta.1+1.21.4

fabric_loader_version=0.16.9
fabric_api_version=0.112.0+1.21.4
modmenu_version=13.0.0-beta.1

neoforge_version=21.4.22-beta

# Compat Mods
rei_version=18.0.796
arch_api=15.0.1
emi_version=1.1.18+1.21.1
jei_minecraft_version=1.21.1
jei_version=19.21.0.247

sodium_version=mc1.21.4-0.6.3

geckolib_minecraft_version=1.21.3
geckolib_version=4.7.1

# Types: none, rei, emi, jei
item_viewer_type=none



