org.gradle.jvmargs=-Xmx4096M

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge

minecraft_base_version=1.21.1

archives_base_name=accessories
mod_version=1.1.0-beta.52
maven_group=io.wispforest

# Libs
endec_version=0.1.5.1
endec_gson_version=0.1.3.1
endec_netty_version=0.1.2
endec_jankson_version=0.1.3.1

owo_version=0.12.15.4+1.21

owo_neo_version=0.12.15.1-beta.6+1.21
ffapi_version=0.104.0+2.0.14+1.21.1
ffloader_version=2.5.29+0.16.0+1.21

cloth_version=15.0.130

fabric_loader_version=0.16.10
fabric_api_version=0.116.0+1.21.1
modmenu_version=11.0.2

neoforge_version=21.1.205

# Compat Mods
rei_version=16.0.754
arch_api=13.0.6
emi_version=1.1.12+1.21
jei_version=19.14.2.147

sodium_version=mc1.21-0.6.0-beta.2-fabric
geckolib_version=4.6.6
curios_version=9.2.2+1.21.1

# Types: none, rei, emi, jei
item_viewer_type=none



